steps:
  - name: "Download"
    operations:
      - type: "download"
        name: "Hell's Kitchen Sound"
        url: "https://www.youtube.com/watch?v=dinyOvO2EEo"
        output: "hk-dramatic-sound.mp4"

  - name: "Process"
    operations:
      - type: "cut"
        name: "Hell's Kitchen Sound"
        input: "/output/hk-dramatic-sound.mp4"
        start: "00:00:01"
        end: "00:00:02"
        output: "hk-dramatic-sound-cut.mp4"
      - type: "convert"
        name: "Hell's Kitchen Sound"
        input: "/output/hk-dramatic-sound.mp4"
        output_format: "mp3"
        output: "hk-dramatic-sound.mp3"
